export default [
  {
    "login": "oscarossesa",
    "id": 7422396,
    "node_id": "MDQ6VXNlcjc0MjIzOTY=",
    "avatar_url": "https://avatars0.githubusercontent.com/u/7422396?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/oscarossesa",
    "html_url": "https://github.com/oscarossesa",
    "followers_url": "https://api.github.com/users/oscarossesa/followers",
    "following_url": "https://api.github.com/users/oscarossesa/following{/other_user}",
    "gists_url": "https://api.github.com/users/oscarossesa/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/oscarossesa/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/oscarossesa/subscriptions",
    "organizations_url": "https://api.github.com/users/oscarossesa/orgs",
    "repos_url": "https://api.github.com/users/oscarossesa/repos",
    "events_url": "https://api.github.com/users/oscarossesa/events{/privacy}",
    "received_events_url": "https://api.github.com/users/oscarossesa/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "nefastock",
    "id": 9110764,
    "node_id": "MDQ6VXNlcjkxMTA3NjQ=",
    "avatar_url": "https://avatars0.githubusercontent.com/u/9110764?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/nefastock",
    "html_url": "https://github.com/nefastock",
    "followers_url": "https://api.github.com/users/nefastock/followers",
    "following_url": "https://api.github.com/users/nefastock/following{/other_user}",
    "gists_url": "https://api.github.com/users/nefastock/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/nefastock/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/nefastock/subscriptions",
    "organizations_url": "https://api.github.com/users/nefastock/orgs",
    "repos_url": "https://api.github.com/users/nefastock/repos",
    "events_url": "https://api.github.com/users/nefastock/events{/privacy}",
    "received_events_url": "https://api.github.com/users/nefastock/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "pgsoto",
    "id": 5505403,
    "node_id": "MDQ6VXNlcjU1MDU0MDM=",
    "avatar_url": "https://avatars2.githubusercontent.com/u/5505403?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/pgsoto",
    "html_url": "https://github.com/pgsoto",
    "followers_url": "https://api.github.com/users/pgsoto/followers",
    "following_url": "https://api.github.com/users/pgsoto/following{/other_user}",
    "gists_url": "https://api.github.com/users/pgsoto/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/pgsoto/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/pgsoto/subscriptions",
    "organizations_url": "https://api.github.com/users/pgsoto/orgs",
    "repos_url": "https://api.github.com/users/pgsoto/repos",
    "events_url": "https://api.github.com/users/pgsoto/events{/privacy}",
    "received_events_url": "https://api.github.com/users/pgsoto/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "eruido",
    "id": 10394146,
    "node_id": "MDQ6VXNlcjEwMzk0MTQ2",
    "avatar_url": "https://avatars3.githubusercontent.com/u/10394146?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/eruido",
    "html_url": "https://github.com/eruido",
    "followers_url": "https://api.github.com/users/eruido/followers",
    "following_url": "https://api.github.com/users/eruido/following{/other_user}",
    "gists_url": "https://api.github.com/users/eruido/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/eruido/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/eruido/subscriptions",
    "organizations_url": "https://api.github.com/users/eruido/orgs",
    "repos_url": "https://api.github.com/users/eruido/repos",
    "events_url": "https://api.github.com/users/eruido/events{/privacy}",
    "received_events_url": "https://api.github.com/users/eruido/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "parrasaldiasmiguel",
    "id": 37194380,
    "node_id": "MDQ6VXNlcjM3MTk0Mzgw",
    "avatar_url": "https://avatars0.githubusercontent.com/u/37194380?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/parrasaldiasmiguel",
    "html_url": "https://github.com/parrasaldiasmiguel",
    "followers_url": "https://api.github.com/users/parrasaldiasmiguel/followers",
    "following_url": "https://api.github.com/users/parrasaldiasmiguel/following{/other_user}",
    "gists_url": "https://api.github.com/users/parrasaldiasmiguel/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/parrasaldiasmiguel/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/parrasaldiasmiguel/subscriptions",
    "organizations_url": "https://api.github.com/users/parrasaldiasmiguel/orgs",
    "repos_url": "https://api.github.com/users/parrasaldiasmiguel/repos",
    "events_url": "https://api.github.com/users/parrasaldiasmiguel/events{/privacy}",
    "received_events_url": "https://api.github.com/users/parrasaldiasmiguel/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "cristiancajiaos",
    "id": 7603575,
    "node_id": "MDQ6VXNlcjc2MDM1NzU=",
    "avatar_url": "https://avatars3.githubusercontent.com/u/7603575?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/cristiancajiaos",
    "html_url": "https://github.com/cristiancajiaos",
    "followers_url": "https://api.github.com/users/cristiancajiaos/followers",
    "following_url": "https://api.github.com/users/cristiancajiaos/following{/other_user}",
    "gists_url": "https://api.github.com/users/cristiancajiaos/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/cristiancajiaos/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/cristiancajiaos/subscriptions",
    "organizations_url": "https://api.github.com/users/cristiancajiaos/orgs",
    "repos_url": "https://api.github.com/users/cristiancajiaos/repos",
    "events_url": "https://api.github.com/users/cristiancajiaos/events{/privacy}",
    "received_events_url": "https://api.github.com/users/cristiancajiaos/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "marcelopoblette-zz",
    "id": 14886159,
    "node_id": "MDQ6VXNlcjE0ODg2MTU5",
    "avatar_url": "https://avatars0.githubusercontent.com/u/14886159?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/marcelopoblette-zz",
    "html_url": "https://github.com/marcelopoblette-zz",
    "followers_url": "https://api.github.com/users/marcelopoblette-zz/followers",
    "following_url": "https://api.github.com/users/marcelopoblette-zz/following{/other_user}",
    "gists_url": "https://api.github.com/users/marcelopoblette-zz/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/marcelopoblette-zz/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/marcelopoblette-zz/subscriptions",
    "organizations_url": "https://api.github.com/users/marcelopoblette-zz/orgs",
    "repos_url": "https://api.github.com/users/marcelopoblette-zz/repos",
    "events_url": "https://api.github.com/users/marcelopoblette-zz/events{/privacy}",
    "received_events_url": "https://api.github.com/users/marcelopoblette-zz/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "franciscoquijada",
    "id": 33910637,
    "node_id": "MDQ6VXNlcjMzOTEwNjM3",
    "avatar_url": "https://avatars0.githubusercontent.com/u/33910637?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/franciscoquijada",
    "html_url": "https://github.com/franciscoquijada",
    "followers_url": "https://api.github.com/users/franciscoquijada/followers",
    "following_url": "https://api.github.com/users/franciscoquijada/following{/other_user}",
    "gists_url": "https://api.github.com/users/franciscoquijada/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/franciscoquijada/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/franciscoquijada/subscriptions",
    "organizations_url": "https://api.github.com/users/franciscoquijada/orgs",
    "repos_url": "https://api.github.com/users/franciscoquijada/repos",
    "events_url": "https://api.github.com/users/franciscoquijada/events{/privacy}",
    "received_events_url": "https://api.github.com/users/franciscoquijada/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "nupipe",
    "id": 56240556,
    "node_id": "MDQ6VXNlcjU2MjQwNTU2",
    "avatar_url": "https://avatars2.githubusercontent.com/u/56240556?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/nupipe",
    "html_url": "https://github.com/nupipe",
    "followers_url": "https://api.github.com/users/nupipe/followers",
    "following_url": "https://api.github.com/users/nupipe/following{/other_user}",
    "gists_url": "https://api.github.com/users/nupipe/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/nupipe/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/nupipe/subscriptions",
    "organizations_url": "https://api.github.com/users/nupipe/orgs",
    "repos_url": "https://api.github.com/users/nupipe/repos",
    "events_url": "https://api.github.com/users/nupipe/events{/privacy}",
    "received_events_url": "https://api.github.com/users/nupipe/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "descobardos",
    "id": 38218096,
    "node_id": "MDQ6VXNlcjM4MjE4MDk2",
    "avatar_url": "https://avatars2.githubusercontent.com/u/38218096?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/descobardos",
    "html_url": "https://github.com/descobardos",
    "followers_url": "https://api.github.com/users/descobardos/followers",
    "following_url": "https://api.github.com/users/descobardos/following{/other_user}",
    "gists_url": "https://api.github.com/users/descobardos/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/descobardos/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/descobardos/subscriptions",
    "organizations_url": "https://api.github.com/users/descobardos/orgs",
    "repos_url": "https://api.github.com/users/descobardos/repos",
    "events_url": "https://api.github.com/users/descobardos/events{/privacy}",
    "received_events_url": "https://api.github.com/users/descobardos/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "cam-arayaf",
    "id": 35781969,
    "node_id": "MDQ6VXNlcjM1NzgxOTY5",
    "avatar_url": "https://avatars2.githubusercontent.com/u/35781969?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/cam-arayaf",
    "html_url": "https://github.com/cam-arayaf",
    "followers_url": "https://api.github.com/users/cam-arayaf/followers",
    "following_url": "https://api.github.com/users/cam-arayaf/following{/other_user}",
    "gists_url": "https://api.github.com/users/cam-arayaf/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/cam-arayaf/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/cam-arayaf/subscriptions",
    "organizations_url": "https://api.github.com/users/cam-arayaf/orgs",
    "repos_url": "https://api.github.com/users/cam-arayaf/repos",
    "events_url": "https://api.github.com/users/cam-arayaf/events{/privacy}",
    "received_events_url": "https://api.github.com/users/cam-arayaf/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "JoaquinMelladoQ",
    "id": 64607908,
    "node_id": "MDQ6VXNlcjY0NjA3OTA4",
    "avatar_url": "https://avatars2.githubusercontent.com/u/64607908?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/JoaquinMelladoQ",
    "html_url": "https://github.com/JoaquinMelladoQ",
    "followers_url": "https://api.github.com/users/JoaquinMelladoQ/followers",
    "following_url": "https://api.github.com/users/JoaquinMelladoQ/following{/other_user}",
    "gists_url": "https://api.github.com/users/JoaquinMelladoQ/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/JoaquinMelladoQ/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/JoaquinMelladoQ/subscriptions",
    "organizations_url": "https://api.github.com/users/JoaquinMelladoQ/orgs",
    "repos_url": "https://api.github.com/users/JoaquinMelladoQ/repos",
    "events_url": "https://api.github.com/users/JoaquinMelladoQ/events{/privacy}",
    "received_events_url": "https://api.github.com/users/JoaquinMelladoQ/received_events",
    "type": "User",
    "site_admin": false
  }
];
